[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_solution = "3XQdG1Zpk151xuGHSd6DUkNuh9m9i3M8ptxJEHNfZdJ2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
